## Welcome to Python!

I know what you are all thinking...finally!

Okay let's check out the basics of Python.

I am typing this inside of Jupyter notebook which yields a markdown/programming environment similar to R markdown.

First let us discuss the basics of Python. Here are our standard types:

In [1]:
3

3

In [2]:
type(3)

int

In [3]:
3.0

3.0

In [4]:
type(3.0)

float

In [5]:
type('c')

str

In [6]:
type('ca')

str

In [7]:
type("ca")

str

In [8]:
True

True

In [9]:
type(True)

bool

In [10]:
type(T) #Not defined unlike R

NameError: name 'T' is not defined

In [11]:
type(true)

NameError: name 'true' is not defined

In [12]:
type(x=3) #An assignment does not return a value. This is different from C/C++/R.

TypeError: type() takes 1 or 3 arguments

In [13]:
x=2 #assignment

In [14]:
x

2

In [15]:
x==3 #Boolean

False

### Lists and dictionaries
Okay let's check out some syntetic data structures. 

In [16]:
y = [4.5,x, 'c'] #lists can contain different types

In [17]:
type(y)

list

In [18]:
y[0] #zero indexing

4.5

In [19]:
y[1]

2

In [20]:
y[-1] #last entry

'c'

In [21]:
y[-2] 

2

In [22]:
len(y)

3

In [23]:
y = y + ['a','b','d']

In [24]:
y

[4.5, 2, 'c', 'a', 'b', 'd']

In [25]:
y[1:3] #Slicing!

[2, 'c']

In [26]:
y[1:4]

[2, 'c', 'a']

In [27]:
y[1:6:2] # jump by twos

[2, 'a', 'd']

In [28]:
y[:] #copy entire list

[4.5, 2, 'c', 'a', 'b', 'd']

In [29]:
z = y

In [30]:
z[1]=3

In [31]:
y

[4.5, 3, 'c', 'a', 'b', 'd']

In [32]:
z = y[:]

In [33]:
z[1]=2

In [34]:
z == y

False

In [35]:
z[1]

2

In [36]:
y[1]

3

In [37]:
z = y[::-1] #Reverse order

In [38]:
z

['d', 'b', 'a', 'c', 3, 4.5]

Now let us look at dictionaries.

In [39]:
a = {'x' : 1, 'y' : z, 'z' : 'entry'}

In [40]:
a

{'x': 1, 'y': ['d', 'b', 'a', 'c', 3, 4.5], 'z': 'entry'}

In [41]:
a['x']

1

In [42]:
a['y'][3]

'c'

In [43]:
a.values()

dict_values([1, ['d', 'b', 'a', 'c', 3, 4.5], 'entry'])

In [44]:
a.keys()

dict_keys(['x', 'y', 'z'])

In [45]:
'abc'+'efg'

'abcefg'

In [46]:
'abc'[2]

'c'

In [47]:
'abcdef'[-2]='x' # strings are immutable (as usual)

TypeError: 'str' object does not support item assignment

In [48]:
'abc'.upper()

'ABC'

There are also tuples, which are non-transformable.

In [49]:
x = (1,2,3)

In [50]:
x

(1, 2, 3)

In [51]:
type(x)

tuple

In [52]:
x[2]

3

In [53]:
x[-2]=3 # Fails

TypeError: 'tuple' object does not support item assignment

### List and dictionary comprehensions

Okay, now some of my favorite features, list and dictionary comprehensions, which allow us to use syntax similar to the mathematician's set notation

In [54]:
w = [ a**2 for a in range(10)]

In [55]:
w

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Note that exponentiation in python is done with the symbol ** 

Also note that the range function works a bit like slicing.

In [56]:
[a for a in range(1,20,2)]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

We can also select subsets:

In [57]:
[a for a in range(1,20) if a % 2 != 0]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

## An example with functions

Just for fun let's see how to build a simple encrypter. First let us import a variable of printable characters from the module string and denote it by chars.

In [58]:
from string import printable as chars

In [59]:
chars

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

In [60]:
lc = len(chars); lc

100

In [61]:
codebook = {chars[i] : chars[(i+lc//2)%lc] for i in range(lc-1)}

There is a couple new things going on in this previous line, so let's unpack it. First we have dictionary comprehension, which is defined like a list comprehension. We have used the integer division operateor // and the integer modulus operator %.

In [62]:
codebook['a']

'Y'

In [63]:
codebook['Y']

'a'

Now we are going to use one of the three core functions from functional programming (map, reduce, filter), namely reduce. This goes through a list item by item and applies a two variable function using an accumulated value for the first argument and the list element for the second. We only need to use this two variable function once, so we will use an anonymous/lambda function. 

Finally, it is important to note the absence of brackets indicating the start and end of the function. Python accomplishes this using spacing. This is very unusual, but in Python spacing has meaning and if you use inconsistent spacing your program will not run.

In [64]:
from functools import reduce

In [65]:
def encode_decode(s):
    return reduce(lambda x,y: x+codebook[y],s,"")

In [66]:
encrypted = encode_decode('This is a secret message'); encrypted

"5&';I';IYI;#!:#<I+#;;Y%#"

In [67]:
encode_decode(encrypted)

'This is a secret message'

### Numpy and Pandas

Unlike R, Python was not designed for statistical analysis. Python was designed as a general purpose high level programming language. However, one of Python's strongest features is an truly vast collection of easy to use libraries (called modules) that drastically simplify our lives.


Two key core pieces of R functionality are lacking. We do not have an analogue of vectors (efficient lists containing only one type of element), so we are also lacking matrices and tensors, which are just fancier vectors. We are also lacking the data frame abstraction which plays a central role in R. 

Vector functionality comes from [numpy](http://www.numpy.org/) which is usually imported as np. This provides fast vectors and vectorized operations and should be used when possible instead of lists of numerical data. Dataframes come from [pandas](http://pandas.pydata.org/pandas-docs/stable/) which is usually imported as pd. Pandas builds on numpy and is part of the [scipy](https://www.scipy.org/) ecosystem, which includes many numerical libraries including more advanced statistics and linear algebra functions. The scipy ecosystem also includes [matplotlib](https://matplotlib.org/) which is a pretty complex/flexible plotting library. I should also mention [scikit-learn](
http://scikit-learn.org/stable/) which is a standard machine learning library (although surprisingly limited) is built on scipy.

In [68]:
import numpy as np

In [69]:
a=np.arange(10)

In [70]:
np.sin(a) # vectorized operation

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

A useful numpy feature (although it takes some getting used to) is broadcasting, which is similar to functionality in R, which automatically converts an array of one shape into another shape when performing various operations according to these [rules](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html). Broadcasting can easiliy lead to bugs and confusion, so try to be careful.

In [71]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
list(range(10))*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [73]:
a*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
a.a

AttributeError: 'numpy.ndarray' object has no attribute 'a'

In [75]:
a.shape

(10,)

In [76]:
b=a.reshape(10,1)

In [77]:
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [78]:
b.T

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [79]:
b.T.shape

(1, 10)

In [80]:
c=np.dot(a,b); c

array([285])

In [81]:
c.shape

(1,)

In [82]:
d=np.zeros(shape=(2,3)); d

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [83]:
e = np.ones_like(d); e

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [84]:
f = np.ndarray(shape = (2,3,4), buffer = np.array(list(range(24))),dtype = np.int)

In [85]:
f

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
f[1,2,3]

23

In [87]:
f[1,1:3,3]

array([19, 23])

In [88]:
f[:,1:3,3]

array([[ 7, 11],
       [19, 23]])

In [89]:
for x in f:
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [90]:
for outer in f:
    for inner in outer:
        for really_inner in inner:
            print(really_inner)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("crypto-markets.csv")

In [3]:
df.head()

slug symbol     name        date  ranknow    open    high     low  \
0  bitcoin    BTC  Bitcoin  2013-04-28        1  135.30  135.98  132.10   
1  bitcoin    BTC  Bitcoin  2013-04-29        1  134.44  147.49  134.00   
2  bitcoin    BTC  Bitcoin  2013-04-30        1  144.00  146.93  134.05   
3  bitcoin    BTC  Bitcoin  2013-05-01        1  139.00  139.89  107.72   
4  bitcoin    BTC  Bitcoin  2013-05-02        1  116.38  125.60   92.28   

    close  volume      market  close_ratio  spread  
0  134.21       0  1500520000       0.5438    3.88  
1  144.54       0  1491160000       0.7813   13.49  
2  139.00       0  1597780000       0.3843   12.88  
3  116.99       0  1542820000       0.2882   32.17  
4  105.21       0  1292190000       0.3881   33.32

In [4]:
df.symbol.unique()

array(['BTC', 'ETH', 'XRP', ..., '9COIN', 'BT1', 'BT2'], dtype=object)

In [5]:
len(df.symbol.unique())

1369

In [6]:
df['symbol'].unique()

array(['BTC', 'ETH', 'XRP', ..., '9COIN', 'BT1', 'BT2'], dtype=object)

In [7]:
small_df = df.head(25)

In [8]:
small_df

slug symbol     name        date  ranknow    open    high     low  \
0   bitcoin    BTC  Bitcoin  2013-04-28        1  135.30  135.98  132.10   
1   bitcoin    BTC  Bitcoin  2013-04-29        1  134.44  147.49  134.00   
2   bitcoin    BTC  Bitcoin  2013-04-30        1  144.00  146.93  134.05   
3   bitcoin    BTC  Bitcoin  2013-05-01        1  139.00  139.89  107.72   
4   bitcoin    BTC  Bitcoin  2013-05-02        1  116.38  125.60   92.28   
5   bitcoin    BTC  Bitcoin  2013-05-03        1  106.25  108.13   79.10   
6   bitcoin    BTC  Bitcoin  2013-05-04        1   98.10  115.00   92.50   
7   bitcoin    BTC  Bitcoin  2013-05-05        1  112.90  118.80  107.14   
8   bitcoin    BTC  Bitcoin  2013-05-06        1  115.98  124.66  106.64   
9   bitcoin    BTC  Bitcoin  2013-05-07        1  112.25  113.44   97.70   
10  bitcoin    BTC  Bitcoin  2013-05-08        1  109.60  115.78  109.60   
11  bitcoin    BTC  Bitcoin  2013-05-09        1  113.20  113.46  109.26   
12  bitcoin    BTC  Bitcoin  2013-05-10        1  112.80  122.00  111.55   
13  bitcoin    BTC  Bitcoin  2013-05-11        1  117.70  118.68  113.01   
14  bitcoin    BTC  Bitcoin  2013-05-12        1  115.64  117.45  113.44   
15  bitcoin    BTC  Bitcoin  2013-05-13        1  114.82  118.70  114.50   
16  bitcoin    BTC  Bitcoin  2013-05-14        1  117.98  119.80  110.25   
17  bitcoin    BTC  Bitcoin  2013-05-15        1  111.40  115.81  103.50   
18  bitcoin    BTC  Bitcoin  2013-05-16        1  114.22  118.76  112.20   
19  bitcoin    BTC  Bitcoin  2013-05-17        1  118.21  125.30  116.57   
20  bitcoin    BTC  Bitcoin  2013-05-18        1  123.50  125.25  122.30   
21  bitcoin    BTC  Bitcoin  2013-05-19        1  123.21  124.50  119.57   
22  bitcoin    BTC  Bitcoin  2013-05-20        1  122.50  123.62  120.12   
23  bitcoin    BTC  Bitcoin  2013-05-21        1  122.02  123.00  121.21   
24  bitcoin    BTC  Bitcoin  2013-05-22        1  122.89  124.00  122.00   

     close  volume      market  close_ratio  spread  
0   134.21       0  1500520000       0.5438    3.88  
1   144.54       0  1491160000       0.7813   13.49  
2   139.00       0  1597780000       0.3843   12.88  
3   116.99       0  1542820000       0.2882   32.17  
4   105.21       0  1292190000       0.3881   33.32  
5    97.75       0  1180070000       0.6424   29.03  
6   112.50       0  1089890000       0.8889   22.50  
7   115.91       0  1254760000       0.7521   11.66  
8   112.30       0  1289470000       0.3141   18.02  
9   111.50       0  1248470000       0.8767   15.74  
10  113.57       0  1219450000       0.6424    6.18  
11  112.67       0  1259980000       0.8119    4.20  
12  117.20       0  1255970000       0.5407   10.45  
13  115.24       0  1311050000       0.3933    5.67  
14  115.00       0  1288630000       0.3890    4.01  
15  117.98       0  1279980000       0.8286    4.20  
16  111.50       0  1315720000       0.1309    9.55  
17  114.22       0  1242760000       0.8708   12.31  
18  118.76       0  1274620000       1.0000    6.56  
19  123.02       0  1319590000       0.7388    8.73  
20  123.50       0  1379140000       0.4068    2.95  
21  121.99       0  1376370000       0.4909    4.93  
22  122.00       0  1368910000       0.5371    3.50  
23  122.88       0  1363940000       0.9330    1.79  
24  123.89       0  1374130000       0.9450    2.00

In [9]:
small_df[['symbol','name']]

symbol     name
0     BTC  Bitcoin
1     BTC  Bitcoin
2     BTC  Bitcoin
3     BTC  Bitcoin
4     BTC  Bitcoin
5     BTC  Bitcoin
6     BTC  Bitcoin
7     BTC  Bitcoin
8     BTC  Bitcoin
9     BTC  Bitcoin
10    BTC  Bitcoin
11    BTC  Bitcoin
12    BTC  Bitcoin
13    BTC  Bitcoin
14    BTC  Bitcoin
15    BTC  Bitcoin
16    BTC  Bitcoin
17    BTC  Bitcoin
18    BTC  Bitcoin
19    BTC  Bitcoin
20    BTC  Bitcoin
21    BTC  Bitcoin
22    BTC  Bitcoin
23    BTC  Bitcoin
24    BTC  Bitcoin

In [10]:
small_df[4:6]

slug symbol     name        date  ranknow    open    high    low  \
4  bitcoin    BTC  Bitcoin  2013-05-02        1  116.38  125.60  92.28   
5  bitcoin    BTC  Bitcoin  2013-05-03        1  106.25  108.13  79.10   

    close  volume      market  close_ratio  spread  
4  105.21       0  1292190000       0.3881   33.32  
5   97.75       0  1180070000       0.6424   29.03

In [11]:
small_df[4] # fails

KeyError: 4

In [12]:
small_df.loc[4]

slug              bitcoin
symbol                BTC
name              Bitcoin
date           2013-05-02
ranknow                 1
open               116.38
high                125.6
low                 92.28
close              105.21
volume                  0
market         1292190000
close_ratio        0.3881
spread              33.32
Name: 4, dtype: object

In [13]:
small_df.loc[4,"open"]

116.38

In [14]:
small_df.iloc[4,4]

1

Pay attention to the syntax for referencing. Think of the loc and iloc objects as dictionaries which will pull up the relevant pieces of the data frame and allow slicing notation (which is now inclusive on both ends). The difference is that loc searches by name and iloc only searches by numerical index.

In [15]:
type(small_df.loc[4:4])

pandas.core.frame.DataFrame

In [22]:
type(small_df.loc[4])

pandas.core.series.Series

In [24]:
df['date'] = pd.to_datetime(df['date'])

In [31]:
df['date'].head()

0   2013-04-28
1   2013-04-29
2   2013-04-30
3   2013-05-01
4   2013-05-02
Name: date, dtype: datetime64[ns]

Select only the first few symbols.

In [38]:
mask = df['symbol'].isin(df['symbol'].unique()[1:5])

In [50]:
import matplotlib.pyplot as plt

In [51]:
fig, ax = plt.subplots()

In [65]:
for mini_df, sym in df[mask].groupby('symbol'):
    

In [66]:
plt.cla()